### ISSUE TITLE
tracePropagationTargets should support custom domains

### ISSUE THREAD

**Issue by MikeShi42** [hyperdxio/hyperdx#10]
If you're hosting the app on a custom domain, our frontend app should be able to set the tracePropagationTargets to the right value. Currently it's hardcoded to only propagate trace headers for localhost or our production domain.

Line that needs to be updated: https://github.com/hyperdxio/hyperdx/blob/main/packages/app/pages/_app.tsx#L38

**Comment by 0-sv** [comment]
Is `tracePropagationTargets` similar to https://docs.sentry.io/platforms/javascript/performance/instrumentation/automatic-instrumentation/#tracepropagationtargets?

If so, is it wise to dynamically set it to the custom domain (my inference from your issue) or should there be a way for the user to configure it using something like `.env`?

**Comment by MikeShi42** [comment]
> Is `tracePropagationTargets` similar to https://docs.sentry.io/platforms/javascript/performance/instrumentation/automatic-instrumentation/#tracepropagationtargets?

Yes! It's exactly the same (based on otel)

> If so, is it wise to dynamically set it to the custom domain (my inference from your issue) or should there be a way for the user to configure it using something like `.env`?

Absolutely! I was a bit hurried in my writing of the issue, but it should definitely be derived from the server url config, right now it's hardcoded to localhost or hyperdx.io which means our frontend app won't be able to propagate trace info for self logging if you're accessing it over the internet.

**Comment by 0-sv** [comment]
So I guess that would be `collectorUrl` from the server url config response?

**Comment by thekartikeyamishra** [comment]
Hi,
Hope this message finds you well, 
I want to work on this issue. Can you assign me this?

**Comment by MikeShi42** [comment]
@0-sv 

You'd want to set the `tracePropagationTargets` to `config.API_SERVER_URL` [from here](https://github.com/hyperdxio/hyperdx/blob/main/packages/app/src/config.ts#L1) as this allows the app's frontend instrumentation to know to propagate the traces to the backend requests.

@thekartikeyamishra - happy to have it assigned to you, let me know if you need any other info for this ticket.

**Comment by wrn14897** [comment]
This should be fixed on main https://github.com/hyperdxio/hyperdx/pull/26/commits/59252abd25b22d75a6c46dc53e2a0874cddf885d
