### ISSUE TITLE
[HDX-166] Persist Bar Chart Display

### ISSUE THREAD

**Issue by MikeShi42** [hyperdxio/hyperdx#114]
Follow up for https://github.com/hyperdxio/hyperdx/pull/89#discussion_r1387606257

> Hello, I quite enjoy the new bar chart, is there a way I can make it default on my graph ? Everytime I reload the page it revert to line mode

Requested by https://discord.com/channels/1149498480893640706/1149498481912840225/1175766814127575080

<sub>[HDX-166](https://linear.app/hyperdx/issue/HDX-166/persist-bar-chart-display)</sub>

**Comment by MikeShi42** [comment]
[https://deploysentinel.slack.com/archives/C067PDJ21SP/p1707926437114039](https://deploysentinel.slack.com/archives/C067PDJ21SP/p1707926437114039)

**Comment by JeyRathnam** [comment]
@MikeShi42 Can I work on this?

**Comment by MikeShi42** [comment]
@JeyRathnam assigned, feel free to ping us if you have any questions/need help! Thank you :)

**Comment by MikeShi42** [comment]
Hi @JeyRathnam are you still looking to work on this? We're considering picking this up if you've gotten too busy to take a look :)

**Comment by JeyRathnam** [comment]
@MikeShi42 apologies, I am occupied with other projects. Will un-assign myself, sorry again.

**Comment by andrewfhart** [comment]
Hi @MikeShi42 - I notice this is still happening when running the latest all-in-one docker image (docker.hyperdx.io/hyperdx/hyperdx-all-in-one). 

The fix for this appears to be localized and straightforward: just need to toggle `showDisplaySwitcher` to `true` and provide the handler to the `DBTimeChart` component on the DBDashboardPage`. 

```diff
diff --git a/packages/app/src/DBDashboardPage.tsx b/packages/app/src/DBDashboardPage.tsx
index 5de171f..dbff5f8 100644
--- a/packages/app/src/DBDashboardPage.tsx
+++ b/packages/app/src/DBDashboardPage.tsx
@@ -317,9 +317,20 @@ const Tile = forwardRef(
               queriedConfig?.displayType === DisplayType.StackedBar) && (
               <DBTimeChart
                 sourceId={chart.config.source}
-                showDisplaySwitcher={false}
+                showDisplaySwitcher={true}
                 config={queriedConfig}
                 onTimeRangeSelect={onTimeRangeSelect}
+                setDisplayType={displayType => {
+                  if (onUpdateChart) {
+                    onUpdateChart({
+                      ...chart,
+                      config: {
+                        ...chart.config,
+                        displayType,
+                      },
+                    });
+                  }
+                }}
               />
             )}
             {queriedConfig?.displayType === DisplayType.Table && (
```

I'm new to the project though, and might be misunderstanding something. Does this approach make sense?
