### ISSUE TITLE
Not able to override app env variables

### ISSUE THREAD

**Issue by NanFengCheong** [hyperdxio/hyperdx#12]
<img width="544" alt="image" src="https://github.com/hyperdxio/hyperdx/assets/7321833/e5663afc-0c23-465c-b03b-6be4d5c3e638">
<img width="851" alt="image" src="https://github.com/hyperdxio/hyperdx/assets/7321833/160e7580-5d05-4240-9fed-0819305b4d1d">

I was trying to setup in server using the docker compose and find out cant replace the localhost with my server hostname.
NEXT_PUBLIC_API_SERVER_URL & NEXT_PUBLIC_HDX_COLLECTOR_URL cant be overriden.
localhost2 is just an example hostname.

**Comment by wrn14897** [comment]
Hi, thanks for contributing to HyperDX. It's because the app service is using pre-built image and some env vars are baked-in. I'm going to update the compose file so people can rebuild the image in this case.

**Comment by aurbina83** [comment]
Also ran into this, except I changed the exposed port on `api` and was trying to pass that in to `app` on the `NEXT_PUBLIC_API_SERVER_URL`.  Awesome that it's getting handled so quickly

**Comment by snjv94** [comment]
> <img alt="image" width="544" src="https://user-images.githubusercontent.com/7321833/268997604-e5663afc-0c23-465c-b03b-6be4d5c3e638.png"> <img alt="image" width="851" src="https://user-images.githubusercontent.com/7321833/268998155-160e7580-5d05-4240-9fed-0819305b4d1d.png">
> I was trying to setup in server using the docker compose and find out cant replace the localhost with my server hostname. NEXT_PUBLIC_API_SERVER_URL & NEXT_PUBLIC_HDX_COLLECTOR_URL cant be overriden. localhost2 is just an example hostname.

@NanFengCheong 
I was able to work it out by replacing the `docker-compose.yml` with `docker-compose.dev.yml`. 
This helped in rebuilding the images from scratch along with the ENV var override.

**Comment by NanFengCheong** [comment]
@snjv94 did you mean you added the build property under app? or just run the docker compose using docker-compose.dev.yml?
<img width="575" alt="image" src="https://github.com/hyperdxio/hyperdx/assets/7321833/4512da6c-bb8c-4123-9bc7-4b5b92e1309e">

**Comment by NanFengCheong** [comment]
> Hi, thanks for contributing to HyperDX. It's because the app service is using pre-built image and some env vars are baked-in. I'm going to update the compose file so people can rebuild the image in this case.

I would prefer the ability to override those variable values using env variables since it is much faster than rebuilding the whole image. But it would be fine as long as the alternatives are available.

**Comment by Cnidarias** [comment]
> > Hi, thanks for contributing to HyperDX. It's because the app service is using pre-built image and some env vars are baked-in. I'm going to update the compose file so people can rebuild the image in this case.
> 
> I would prefer the ability to override those variable values using env variables since it is much faster than rebuilding the whole image. But it would be fine as long as the alternatives are available.

There are some more discussions going on about this here in the MR that I opened

**Comment by NanFengCheong** [comment]
> > > Hi, thanks for contributing to HyperDX. It's because the app service is using pre-built image and some env vars are baked-in. I'm going to update the compose file so people can rebuild the image in this case.
> > 
> > 
> > I would prefer the ability to override those variable values using env variables since it is much faster than rebuilding the whole image. But it would be fine as long as the alternatives are available.
> 
> There are some more discussions going on about this here in the MR that I opened

Ya, I saw that. I dont see the purpose of adding traefik in the docker compose since everyone has their own preference/setup. As long as all the env variables with localhost can be override with the hostname, it should be fine. 

<img width="445" alt="image" src="https://github.com/hyperdxio/hyperdx/assets/7321833/9c735256-9b5f-445a-9c7d-792307cdf006">

I think you miss out NEXT_PUBLIC_HDX_COLLECTOR_URL variable, it should be connected to the server hostname instead of localhost.

**Comment by snjv94** [comment]
> @snjv94 did you mean you added the build property under app? or just run the docker compose using docker-compose.dev.yml? <img alt="image" width="575" src="https://user-images.githubusercontent.com/7321833/269289671-4512da6c-bb8c-4123-9bc7-4b5b92e1309e.png">

@NanFengCheong merely using docker-compose.dev.yml instead of docker-compose.yml will rebuild the images for you. If you open the dev docker-compose file, you will see the custom added context build file there.
You can use this till the time it gets fixed.

**Comment by NanFengCheong** [comment]
> > @snjv94 did you mean you added the build property under app? or just run the docker compose using docker-compose.dev.yml? <img alt="image" width="575" src="https://user-images.githubusercontent.com/7321833/269289671-4512da6c-bb8c-4123-9bc7-4b5b92e1309e.png">
> 
> @NanFengCheong merely using docker-compose.dev.yml instead of docker-compose.yml will rebuild the images for you. If you open the dev docker-compose file, you will see the custom added context build file there. You can use this till the time it gets fixed.

@snjv94 ok, I am able to override the env variables after build

**Comment by aurbina83** [comment]
> > > @snjv94 did you mean you added the build property under app? or just run the docker compose using docker-compose.dev.yml? <img alt="image" width="575" src="https://user-images.githubusercontent.com/7321833/269289671-4512da6c-bb8c-4123-9bc7-4b5b92e1309e.png">
> 
> > 
> 
> > @NanFengCheong merely using docker-compose.dev.yml instead of docker-compose.yml will rebuild the images for you. If you open the dev docker-compose file, you will see the custom added context build file there. You can use this till the time it gets fixed.
> 
> 
> 
> @snjv94 ok, I am able to override the env variables after build

I think the idea is being able to pull down the images from the image repository and override variables without having to pull down the source code. I know the latter solves the problem in the short term, but the idea of this issue is to fix it long term (using images without pulling down code base)

**Comment by ldominguezBold** [comment]
I my case only change the FRONT to be built... to to be built must add the ARGS to the built. The problem is that on build time this variable is set, so there is not (only coding) other way to set that API URL on front.
And like production changed all `development` by `production` for NODE_ENV

**Comment by Cnidarias** [comment]
Another suggestion for solving the issue (in regards to having env values in the frontend)

We have a plain `env.js` file that is then included in the `index.html` (we are using angular - so this is rather trivial to setup).

The `env.js` file looks something like this

```javascsript
(function (window) {
    window._env = window._env || {};
    window._env.variable= '${VARIABLE}';
})(this);
```

And then inside of the frontend docker container - we run a simple `envsubst` on the file before serving - in our case we host our compiled dashboards on nginx - so we have something like this as our `docker-entrypoint.sh`
e.g.

```bash
# shortened for brevity 
envsubst '${VARIABLE}' < env.js > env.js.tmp && mv env.js.tmp env.js

nginx -g 'daemon off;'
```
This does feel a bit hacky - but works great nonetheless 😄 

So maybe that could be another solution that'd be worth looking at for you.

**Comment by wrn14897** [comment]
> > > @snjv94 did you mean you added the build property under app? or just run the docker compose using docker-compose.dev.yml? <img alt="image" width="575" src="https://user-images.githubusercontent.com/7321833/269289671-4512da6c-bb8c-4123-9bc7-4b5b92e1309e.png">
> > 
> > 
> > @NanFengCheong merely using docker-compose.dev.yml instead of docker-compose.yml will rebuild the images for you. If you open the dev docker-compose file, you will see the custom added context build file there. You can use this till the time it gets fixed.
> 
> @snjv94 ok, I am able to override the env variables after build

We'd not suggest to use dev build for the production since the app isn't very performant and it doesn't stand alone (without source code volume mount) in dev build (theoretically you can update `target` to `prod`) if you really want to build using compose file. We are going to ship the helper command in Makefile so you can build with the custom URLs.

**Comment by wrn14897** [comment]
Going to update the README. Now users should be able to change app/api URLs or ports in `.env` and run `make build-local` to rebuild images

**Comment by jakoss** [comment]
@wrn14897 But can we change the url's without rebuilding images? Just passing a proper ENV variable to existing image should work fine

**Comment by wrn14897** [comment]
> @wrn14897 But can we change the url's without rebuilding images? Just passing a proper ENV variable to existing image should work fine

That would be ideal. The only one blocker is the api url baked in during the build time (https://github.com/hyperdxio/hyperdx/blob/593c4ca758d896d11854a9c7f4e66bbf9be0134b/packages/app/src/api.ts#L37). Thus rebuilding the app image is still required.

**Comment by jakoss** [comment]
It's always the frontend, isn't it... Is there no way to work around that?

**Comment by wrn14897** [comment]
Yes, its mainly for the frontend app. Probably not at this moment unless we do something on the network layer.

**Comment by sharpSteff** [comment]
> It's always the frontend, isn't it... Is there no way to work around that?

honestly I hate this so much. I run pretty much every service behind a reverse proxy and every service with server-side rendering works just fine.

**Comment by MikeShi42** [comment]
Hi @sharpSteff! Totally hear you on this, we've had some further discussion on discord in exploring being able to use things like using `next-runtime-env` (thanks to lennart!) to help populate these values at run time instead (since there's still some SSR going on with Next anyways). It's going to involve a few changes and some thorough testing so we just haven't had the chance to have a go at it yet - though we're of course always happy to accept PRs/chat further if anyone is opening to taking a swing at it.
