### ISSUE TITLE
Limit registrations/logins for specific emails 

### ISSUE THREAD

**Issue by conbrad** [hyperdxio/hyperdx#13]
Any way to limit the OSS self-hosted version to specific emails?

**Comment by MikeShi42** [comment]
Not for the original setup, but the permission model is that any future user who wants to log in to your self hosted instance must have been invited by the original user (which should achieve what you're looking for in restricting user access to the instance)

Unless you're thinking of restricting by domain even for the original account to be created?

**Comment by conbrad** [comment]
Hey Mike, thanks for the response!

> the permission model is that any future user who wants to log in to your self hosted instance must have been invited by the original user (which should achieve what you're looking for in restricting user access to the instance)

Yes that'd work for my circumstance. I didn't know it behaved like that as I've just tried running the docker compose setup locally and saw I could register as a user freely. I'm looking to apply the helm chart to a kubernetes cluster where I'd want to limit user access as described above. Is there a way I can verify the invite-only behaviour locally?

**Comment by MikeShi42** [comment]
You can verify that the invite flow works locally by going to the team setting page and trying to invite someone (it'll give you a invite link token) - which will help verify the invite flow.

For new registration, we hide it after the setup but if you go to /register, it should deny any new user registrations on the API side.

Edit: we don't have a public helm yet but would love to have help if you'd be open to contributing one, I wasn't sure if your comment was referencing you're putting together a helm chart?

**Comment by conbrad** [comment]
Ok thanks, will try that out.

> we don't have a public helm yet but would love to have help if you'd be open to contributing one, I wasn't sure if your comment was referencing you're putting together a helm chart?

Ah sorry I meant the opentelemetry helm chart in the docs: https://www.hyperdx.io/docs/install/kubernetes#deploying-the-opentelemetry-collector

I may have some cycles this week though if you're looking for a specific helm contribution?

Edit: Oh I see, the app itself just has a `docker-compose` setup -- I could try to find some time to make a helm chart for it.

**Comment by MikeShi42** [comment]
@conbrad just curious if the existing auth worked out for the issue? If so I'll go ahead and close this :)

As for Helm - it isn't a huge deal, I just figured if you were doing something similar it'd be awesome to get a chance to share it, otherwise it's all good!

**Comment by conbrad** [comment]
Hey Mike, yeah thanks, I can close it -- I experimented the other day with building some kubernetes templates as a start, but should note that my current environment is specifically openshift so not sure if that'd be useful to include here.
