### ISSUE TITLE
[HDX-410] Support Otel gRPC

### ISSUE THREAD

**Issue by Seikilos** [hyperdxio/hyperdx#236]
Hi,

to evaluate what types of metrics I can send to hyperdx I realized that I am lacking performance monitoring of my setup. Basically a simple cpu and mem usage, but also more complex cases like container resource usages.
While researching I found various solutions that can send telemetry data (e.g. [Telegraf ](https://github.com/influxdata/telegraf/blob/release-1.29/plugins/outputs/opentelemetry/README.md)) to otel endpoints.

However, I noticed multiple times that those implementers decided to go with otel via gRPC and as far as I know, hyperdex only consumes otel via http. This is not an issue for custom instrumentations I write for my software, but may introduce friction when using third party integrations, that does not support otel over http.

So I would propose to consider adding gRPC support to hyperdx

<sub>[HDX-410](https://linear.app/hyperdx/issue/HDX-410/support-otel-grpc)</sub>

**Comment by wrn14897** [comment]
HyperDX does support gRPC at port `4317`. Can check out the config here https://github.com/hyperdxio/hyperdx/blob/6b68f4c97b2c48acc614611f27cec06bb26aab35/docker/otel-collector/config.yaml#L9-L13
