### ISSUE TITLE
[HYP-39] request size did not match content length

### ISSUE THREAD

**Issue by AvinashUtekar** [hyperdxio/hyperdx#24]
![image](https://github.com/hyperdxio/hyperdx/assets/87367466/594061d6-b5d8-4e3d-839c-92ec678e2484)

i have added hyperdx in nodejs project now i am getting this error on api call , specifically for PUT,POST requests

<sub>[HYP-39](https://linear.app/hyperdx/issue/HYP-39/request-size-did-not-match-content-length)</sub>

**Comment by MikeShi42** [comment]
Any chance you can share a bit more where this error is being thrown, what instrumentation/SDK are you using, and any other repro steps?

**Comment by parzival418** [comment]
I can confirm that this is a bug.  We were using the node-opentelemetry package on our open-source project Magick (https://github.com/Oneirocom/Magick) and we started getting this error message one a handful of different requests.  Often ones with very large payloads, though also in some other odd places.  I hunted for a few days to figure it out, and when I came by this issue, I turned off called the SDK and the bug immediately went away. 

For us though it only happened on heroku, though I didn't actually try running with opentelemetry locally.

**Comment by MikeShi42** [comment]
@michaelsharpe ah got it okay the backend instrumentation is causing the client to throw bad requests on specific network requests.

I'm going to see if we can repro, I'm suspecting it's an issue with `advancedNetworkCapture`. Thank you so much for the extra info, and apologies for making you have to hunt around to figure out this issue.

**Comment by parzival418** [comment]
@MikeShi42 No worries and thanks so much!  Any status on when this might get pushed through?  Would love to get your sweet logging back up and working on my server :)

**Comment by MikeShi42** [comment]
@michaelsharpe sorry this has been so much more elusive than we thought and we've picked/set this one down a few times in the process.

It just hit us- do you happen to have a repro or any repro details you could share for magick? Would be much nicer if we can just spin up your project and actually repro this issue locally.

**Comment by wrn14897** [comment]
hi @michaelsharpe @AvinashUtekar, the issue should be fixed (https://github.com/hyperdxio/hyperdx-js/pull/75). Could you try upgrading the hyper otel sdk to latest (v0.4.2) ? Once you confirm the fix then we can close the issue :)

**Comment by parzival418** [comment]
@wrn14897 Man I am so sorry to have dropped the ball on this! I had totally forgotten about this issue, and was setting up a fresh deploy of my application and started getting the same error.  Bashed my head for a while until I remembered this.  I updated my package and it is all working like a charm.  You guys rock!
