### ISSUE TITLE
[HYP-21] PHP Support

### ISSUE THREAD

**Issue by SamGoody** [hyperdxio/hyperdx#25]
Suggestion: Add support for PHP.

The OpenTelemetry PHP package is more complete than Python's or Go's, the community is larger than Python's or Go's (though Python has  more mindshare), and the number of competitors that support PHP tracing is tiny (erm, that lack of mindshare hurts).

If you are looking to tap into a latent but powerful market with relative ease - add support for tracing PHP!

<sub>[HYP-21](https://linear.app/hyperdx/issue/HYP-21/php-support)</sub>

**Comment by MikeShi42** [comment]
Hi @SamGoody - huge fan of PHP myself, it was my first programming language on the web :)

We support all OpenTelemetry traces as long as they're compliant with the standard, and it should be language agnostic! Can you share any issues you ran into setting up the PHP OpenTelemetry SDK and forwarding traces to HyperDX? Would love to know if there's something PHP-specific we're missing there!

**Comment by SamGoody** [comment]
I have not tried.

I saw you on HN and figured I would check it out.   
(My only past experience was with Sentry, and that a pretty limited attempt.)

On your webpage there was nothing hinting at support beyond what was listed - so I left the comment and moved on.

I suggest you add that you support PhP and other languages that use in to OpenTelemetry.

I won't be able to test over the next few weeks, but will check it out afterwards.

Thank you.

**Comment by oscarmorrison** [comment]
@MikeShi42 is a sdk support coming for php (ideally a laravel package). 
We would be interested in something like this and moving away from new relic/sentry
