### ISSUE TITLE
Customize font and colors

### ISSUE THREAD

**Issue by MikeShi42** [hyperdxio/hyperdx#30]
Some users have a preference for different fonts (monospace vs sans serif) and colors as well. We should allow users to customize their display - likely similar to an editor.

Example feedback from HN: https://news.ycombinator.com/item?id=37562134

Implementation details are likely to be similar to https://github.com/hyperdxio/hyperdx/issues/29

Opening this to feedback as well in terms of what kinds of font/color/customizations people would be looking for :)

**Comment by nanocat-net** [comment]
I'd like this very much. I like a monospaced font for the log display, but I'd love the be able to pick something more comfortable for the UI itself!

**Comment by MikeShi42** [comment]
Implemented in https://github.com/hyperdxio/hyperdx/pull/413
