### ISSUE TITLE
[HDX-491] [HDX-492] Support Structured Search over Span Events

### ISSUE THREAD

**Issue by MikeShi42** [hyperdxio/hyperdx#304]
Today if users send a span event with structured properties, we don't have a mechanism to allow them to search for it in a structured manner.

> Hello, how could I search for span event with level WARN ? level:warm does not return any result. To make it extra clear, I have a row with level ok, but when inspecting this span inside I have a span event with level WARN, this is what I would like my dashboard to show.

https://discord.com/channels/1149498480893640706/1149500035403350036/1204801958809047120

<sub>[HDX-492](https://linear.app/hyperdx/issue/HDX-492/support-structured-search-over-span-events)</sub>

**Comment by Resonious** [comment]
I'm curious why this is not planned. I have an Axum project where `tracing::info!("...")` calls and such create span events, and I would love to be able to search them. I guess I should change my opentelemetry setup so that those create logs instead?

**Comment by MikeShi42** [comment]
@Resonious this was just closed due to staleness in our Linear backlog. WIth v2 actually you should be able to query span events using SQL at least, and probably Lucene as well though I have not tested myself. Are you using v2 or v1 currently?

**Comment by Resonious** [comment]
Looks like still v1! The containers all have 1.10 in the version number. 

Perhaps I'll try spinning up v2

**Comment by AlexBoyd** [comment]
I gave this a quick test locally and I can't seem to get the lucene style to query for the events. 

It seems to struggle to deal with the array typed fields and throws exceptions that every field should be a tuple or array of tuples and the types array of timestamps or array of strings aren't handled somewhere internally. 

I get slightly different errors based on what queries I try. 

Trying to do something like Events.Name.0:"Event name" gives me the error: First argument for function tupleElement must be tuple or array of tuple. Actual Array(String)

Just trying to do a full text search on Events itself gives:

Illegal type Array(Tuple(Timestamp DateTime64(9), Name String, Attributes Map(String, String))) of argument of function ilike

An existence search on events like Events:* does seem to work though to filter for traces with events on them. 

The data for the events is there on the column data, but not shown anywhere in the main tracing visualization or event details overview.

Overall a few ideas to add a little polish to support span events fully other than just adding some test coverage and fixes for lucene searching. 

Firstly, it would be really nice to add some sort of UI element in the tracing visualization for events such as a vertical line in that span at the correct timestamp that could be clicked to view the event would be a nice detail, and seeing the events in the events Event Details overview when you click on the related span. That sort of thing is currently how jaegar tends to visualize things and it works very well. 

I haven't investigated yet what a correlated log looks like in the tracing tab, but maybe UI for that could be reused is there is already something similar.
