### ISSUE TITLE
tracePropagationTargets property in Browser JS

### ISSUE THREAD

**Issue by bldev2473** [hyperdxio/hyperdx#368]
What value should be set in `tracePropagationTargets` in Browser JS?

It appears that the `url` property is intended for the OTEL collector, with the default value being the central hyperdx server, yet I still can't find any guidance in the documentation regarding setting this URL.

**Comment by MikeShi42** [comment]
Hi @bldev2473! Thanks for that feedback, I've just drafted up some new documentation to add to our site about the options in general for the `init` call in the Browser SDK. The `tracePropagationTargets` should be set to your backend API URL, what it does is that the SDK will attach a `traceparent` header to any URL matching one of the regexes specified in `tracePropagationTargets`. This ensures the backend can properly extract and propagate the trace ID, allowing you to link requests between the frontend and backend.

Here's some more details on the init options in general that I'll be adding soon:

#### Options

- `apiKey` - Your HyperDX Ingestion API Key.
- `service` - The service name events will show up as in HyperDX.
- `tracePropagationTargets` - A list of regex patterns to match against HTTP requests to link frontend and backend traces, it will add an additional `traceparent` header to all requests matching any of the patterns. This should be set to your backend API domain (ex. `api.yoursite.com`).
- `consoleCapture` - (Optional) Capture all console logs (default `false`).
- `advancedNetworkCapture` - (Optional) Capture full request/response headers and bodies (default false).
- `url` - (Optional) The OpenTelemetry collector URL, only needed for self-hosted instances.
- `maskAllInputs` - (Optional) Whether to mask all input fields in session replay (default `false`).
- `maskAllText` - (Optional) Whether to mask all text in session replay (default `false`).

**Comment by bldev2473** [comment]
Hi @MikeShi42, thank you for your detailed response. It helped a lot!
