### ISSUE TITLE
[HDX-605] Reset Initial User Password

### ISSUE THREAD

**Issue by MikeShi42** [hyperdxio/hyperdx#369]
In the self-hosted OSS version of the app, if a user creates a team and then subsequently loses their login credentials, it's not possible to reset their password. 

We should introduce some "break glass in case of emergency" way of doing a password reset, possibly a CLI tool they can run locally so they can reset a user's password (ex. generating a reset token in the CLI).

<sub>From [SyncLinear.com](https://synclinear.com) | [HDX-605](https://linear.app/hyperdx/issue/HDX-605/reset-initial-user-password)</sub>

**Comment by jaysonsantos** [comment]
For those needing this, you can execute the following in the container:

```bash
cd /app/api/packages/api/build

 node -e 'const config = require("./config"); const u = require("./models/user").default; const m = require("mongoose"); const main = async () => {const conn = await m.connect(config.MON
GO_URI); const me = await u.findOne({email: "YOUR_EMAIL"}); console.log(me); await me.setPassword("YOUR_PASSWORD"); await me.save(); console.log("bye")}; main()'
```
