### ISSUE TITLE
style(ui): improve text representation for null or N/A values

### ISSUE THREAD

**Issue by mark-omarov** [hyperdxio/hyperdx#37]
The original improvement idea:

>1. It'd be awesome if the value is `N/A`, that we assign the class as `text-muted` so it's less distracting in the UI.
>2. I think `null` might work better than `N/A` in the UI, since it is technically null (though I know in the DB it isn't actually nullable, due to performance reasons)

_Originally posted by @MikeShi42 in https://github.com/hyperdxio/hyperdx/pull/28#pullrequestreview-1640755638_

Indeed, it'd be great to emphasize such values visually.
I'm not really sure if the values should be `null`. My concern is that such a value would look like something went wrong in the code, and I could see myself reporting a bug titled "null value in the duration column of the log table" if I didn't know this was intentional. I guess it depends on how we look at it.
What do you think?

**Comment by mark-omarov** [comment]
Here are some examples using "N/A", "NULL", and "null" as a value.
<details>
<img width="700" alt="Screenshot 2023-09-25 at 9 49 36" src="https://github.com/hyperdxio/hyperdx/assets/15357910/6c249812-2d36-4250-9bec-8838e63eaac9">
<img width="700" alt="Screenshot 2023-09-25 at 9 49 21" src="https://github.com/hyperdxio/hyperdx/assets/15357910/808f56b8-28b4-4ba6-a6c2-5d677587ce52">
<img width="700" alt="Screenshot 2023-09-25 at 9 49 52" src="https://github.com/hyperdxio/hyperdx/assets/15357910/f0dd9ef1-803a-4926-be2f-30def24d4eb0">
</details>

**Comment by MikeShi42** [comment]
I do agree with your sentiment on discord at least `NULL` is less likely to be assumed that it's a UI mistake :)
