### ISSUE TITLE
UX improvement on auth screen 

### ISSUE THREAD

**Issue by rtpa25** [hyperdxio/hyperdx#39]
![Screenshot 2023-09-23 at 12 40 36 PM](https://github.com/hyperdxio/hyperdx/assets/72537293/38bac5ec-e6d4-47c0-abb3-b96f06652183)
Can add the traditional eye icon on the password field so improve UX

**Comment by Sanyam-jain30** [comment]
Can you please assignee it to me.

**Comment by wrn14897** [comment]
This is done
