### ISSUE TITLE
Data retention of OSS version

### ISSUE THREAD

**Issue by shan-mx** [hyperdxio/hyperdx#393]
Hi, thanks for the great work. I'm curious about the default data retention days of OSS version, and whether there's a way to customize it?

**Comment by wrn14897** [comment]
Hi @shan-mx, thanks for bringing this issue up. The default data retention is a month (source: https://github.com/hyperdxio/hyperdx/blob/276957646be5ffc26063cd815aaf6255693c9948/packages/api/src/clickhouse/index.ts#L283). We should make it obvious to customize the data retention. Currently the way to do it is to run a command to update the clickhouse tables schema:
1. Access ClickHouse Client:
```
docker compose exec ch-server clickhouse-client
```
2. Customize Data Retention:

Let's say we want to bump the retention to 90 days.

- Logs/Spans
```
ALTER TABLE log_stream MODIFY  TTL toDateTime(_created_at) + INTERVAL 90 DAY DELETE
```
- Metrics
```
ALTER TABLE metric_stream MODIFY  TTL toDateTime(_created_at) + INTERVAL 90 DAY DELETE
```

Hope this is helpful :)

**Comment by shan-mx** [comment]
@wrn14897 Thank you for your detailed response. It's very helpful to me!

**Comment by patademahesh** [comment]
@wrn14897 Thank you. It's very helpful!
