### ISSUE TITLE
Running HyperDx without ingestion key

### ISSUE THREAD

**Issue by sharpSteff** [hyperdxio/hyperdx#407]
Is it possible to run hyperdx without ingestion key?

I'm considering moving my otlp stack from signoz to hyperdx.
However my already deployed clients (mostly desktop apps) do not have any ingestion key set.

**Comment by MikeShi42** [comment]
I think the closest to doing this out of the box would be to use [local mode](https://github.com/hyperdxio/hyperdx/blob/main/LOCAL.md), though probably not exactly the solution you're looking for.

Alternatively, you can modify the collector config to have the manually attached in this line of code: https://github.com/hyperdxio/hyperdx/blob/4176710570a7288337910e9f8762dc4a10f6664b/docker/otel-collector/config.yaml#L31

To something like:
```
- key: __HDX_API_KEY
   value: "<YOUR_KEY_HERE>"
   action: upsert
```

Then you can mount in your modified config file into the container to overwrite its default config located at `/etc/otelcol-contrib/config.yaml`. Alternatively, you can bake it in by building your own collector image.

If modifying the otel collector isn't possible, there should be a few env vars you can enable on the containers to try to bypass key checks in the ingestion pipeline, though the otel collector way is a bit more reliable imo.

**Comment by sharpSteff** [comment]
@MikeShi42 on first sight changing the otel-collector config worked!! Thanks!
