### ISSUE TITLE
Line Chart Builder - Perform regex on Distinct by - Property

### ISSUE THREAD

**Issue by sharpSteff** [hyperdxio/hyperdx#409]
I'm currently try to migrate from signoz to hyperdx and stumple over this.
I have a property on my span "service.instance.id", which I need to perform a regex on and run a Distinct by query with the result.
![image](https://github.com/hyperdxio/hyperdx/assets/30927510/e15dfc1a-bb60-4ded-a6d5-16586735a252)

Is there a way to do this?
I don't mind to hardcode the functionality as a seperate operation 🤣

**Comment by MikeShi42** [comment]
@sharpSteff unfortunately not today in the app, we've discussed this a bit but it's somewhat of a hairy problem!

The current workaround is to use the otel collector directly to transform the attribute at ingestion time, this will of course also help make the query a lot faster too. Totally understand though that it doesn't solve the case of needing to do it on an ad-hoc basis.

**Comment by sharpSteff** [comment]
@MikeShi42 thanks for clarification. I added my usecase hardcoded as an additional operation and it works like a charme
