### ISSUE TITLE
feat(app): enhanced registration form validation

### ISSUE THREAD

**Issue by mark-omarov** [hyperdxio/hyperdx#44]
We expect passwords to adhere to a ruleset during registration, but we don't give the user enough information.

When registering with a weak password, we receive the "Email or password is invalid". We could add form validation to give the user a better experience by rendering the ruleset for the password when it doesn't match the minimum requirements.

We already use `react-hook-form` on the client and `zod` on the server. We could either use those on the client to validate before submission or improve error messaging after the submission. I would try to leverage `zod` instead of `isemail` and potentially remove the latter, and the same goes for the password validation instead of the custom `validatePassword`.

_I'd be willing to implement this feature._

<img width="415" alt="Screenshot 2023-09-25 at 9 29 31" src="https://github.com/hyperdxio/hyperdx/assets/15357910/a9555fe3-23b7-46a4-a314-17303d1d7b02">

**Comment by wrn14897** [comment]
Can be a separated ticket. I think we should also enforce a strong password policy:
1. at least 12 chars
2. mixed cases
3. includes at least one number
4. includes at least one special char

**Comment by mark-omarov** [comment]
Agreed 👍 
I can do that as part of this issue.

**Comment by mark-omarov** [comment]
Just a follow up - I am still going to deliver this. Life things happened and I'm away for a while, but I'm gonna get back to this and more as soon as possible. It's a shame I'm missing the hacktoberfest 😭

**Comment by wrn14897** [comment]
Hi @mark-omarov, we are going to work on the password policy thing. I'd like to ensure it doesn't overlap with your current work. Could you confirm if you're still actively working on this ticket, or should I consider reassigning it to another contributor?

**Comment by mark-omarov** [comment]
Hi @wrn14897, it was stale for a while, but I'm back and it's close to completion. I plan to raise a PR by Monday latest.

**Comment by wrn14897** [comment]
> Hi @wrn14897, it was stale for a while, but I'm back and it's close to completion. I plan to raise a PR by Monday latest.

Awesome, thanks. Ping me if you need any pointers.

**Comment by mark-omarov** [comment]
Hi @wrn14897, it's ready for CR. Some things I wish I've done better but I don't want to block anyone at this point, I can always re-iterate later.
