### ISSUE TITLE
How can stop the session replay ?

### ISSUE THREAD

**Issue by 729993031** [hyperdxio/hyperdx#471]
Is your feature request related to a problem? Please describe.
when i watch the [document](https://www.hyperdx.io/docs/install/browser#send-custom-actions)，I not found how to close the session play，only use Error Monitoring to the frontEnd.

Describe the solution you'd like
Can close the session play，only use Error Monitoring to the frontEnd.

Describe alternatives you've considered
Provider [Configurations ](https://docs.sentry.io/platforms/javascript/session-replay/#lazy-loading-replay)to close the session play

**Comment by wrn14897** [comment]
Hey @729993031, we do have the support but didn't put that in the doc yet. To disable replay, you can set `disableReplay` to true. Here is the code snippet:

```
HyperDX.init({
  disableReplay: true,
  // rest of configs
});
```

Meanwhile we are going to update the doc. Thanks
