### ISSUE TITLE
Helm Chart

### ISSUE THREAD

**Issue by girish332** [hyperdxio/hyperdx#485]
Is there a Helm Chart available to Deploy hyperdx? The documentation says to install a opentelemetry helm chart and then create your own deployment resource. Won't it be handy if there is a helm chart which already does this for you? 

If there is a requirement to create a custom helm chart I can work on it.

**Comment by MikeShi42** [comment]
Hi @girish332 - if you're looking to deploy HyperDX the app itself (not the OpenTelemetry collectors), we have a community maintained version here: https://github.com/pintoinc/hyperdx-helm

I've just shared some of our reasoning as to why we don't have it in our main repo yet here if you're interested: https://github.com/hyperdxio/hyperdx/pull/325#issuecomment-2308086059 (with any further discussion I'm redirecting to #74)
