### ISSUE TITLE
Documentation or Blog for monitoring LLM Stack using HyperDx

### ISSUE THREAD

**Issue by patcher9** [hyperdxio/hyperdx#487]
Hello team!

## Background
I am Patcher and one of the maintainer of [OpenLIT](https://github.com/openlit/openlit). OpenLIT is an OTel native LLM tool that allows developers to configure complete LLM Observability in single line of code. OpenLIT has also been used in the [official OTel Blog about LLM Observability](https://opentelemetry.io/blog/2024/llm-observability/). 

## Problem
Currently their is no official HyperDx guide either as a Doc or Blogpost that can guide users towards LLM Observability with HyperDX. 

## Proposal

Since our SDK generates OTel traces and Metrics, we have also tested it works very nicely with HyperDX. I was looking to add a guide that can help HyperDX users monitoring their LLM applications.  Can someone from the team help on how can I assist in developing a guide as I don't see any official process on contributing a doc or a guide?

**Comment by MikeShi42** [comment]
Hi @patcher9! Would love to collaborate on a guide, we haven't finished migrating the docs workflow into an OSS repo yet (it's still tied to our cloud hosted stuff). In the interim we've accepted outside contributions in markdown format. I'm happy to collaborate over email to chat more about it, feel free to ping me at mike@hyperdx.io.

**Comment by amanagarwal042** [comment]
Thanks @MikeShi42 , I have sent you an email!

**Comment by MikeShi42** [comment]
Published! Thank you :)

https://www.hyperdx.io/docs/install/openlit
