### ISSUE TITLE
Where's the actual code?

### ISSUE THREAD

**Issue by ally9335** [hyperdxio/hyperdx#488]
There're only built docker images. What's inside them, how can one know?

**Comment by MikeShi42** [comment]
For ease-of-use, we include the pre-built images references in `docker-compose.yml`, but you can see how the images are built in the [dev version of the file here](https://github.com/hyperdxio/hyperdx/blob/main/docker-compose.dev.yml). The bulk of the source code is in the folders here: https://github.com/hyperdxio/hyperdx/tree/main/packages with a few config files for the other container we don't build here: https://github.com/hyperdxio/hyperdx/tree/main/docker

You can also learn more about building the code in our [contributing doc](https://github.com/hyperdxio/hyperdx/blob/main/CONTRIBUTING.md).

**Comment by ally9335** [comment]
> The bulk of the source code 

The bulk or the whole source code? @MikeShi42 

If I was to launch the project locally **without docker**, how would I do this? Would I be able to?

**Comment by MikeShi42** [comment]
> The bulk or the whole source code?

Everything you need to build the local version is available in this repo, you can follow the contributing instructions to see how. So I assume that qualifies as the whole source code, though I'm not really sure what's being asked.

> If I was to launch the project locally without docker, how would I do this? Would I be able to?

You can, but it's not a officially supported deployment option as there's a number of dependencies involed, you can reference the hyperdx-local dockerfile for an example of how you might do so: https://github.com/hyperdxio/hyperdx/blob/main/docker/local/Dockerfile
