### ISSUE TITLE
Commit package.lock or similar

### ISSUE THREAD

**Issue by julionav** [hyperdxio/hyperdx#495]
I noticed the project doesn't commit any lockfiles for any package manager.

This file should be tracked to make sure everyone is using exactly the same dependency versions (package.json usually only defines dependency ranges)

I could make a PR but I am not sure what package manager the team uses, so it would be better if a core contributor does it.

**Comment by MikeShi42** [comment]
Ah something we probably should mention on the contributing doc, we use yarn workspaces which keeps a global yarn.lock file across all our packages which means our lock file is here: https://github.com/hyperdxio/hyperdx/blob/main/yarn.lock as opposed to being in the packages themselves. You can still use yarn within the package directories, it'll continue to update the yarn.lock file globally for you.
