### ISSUE TITLE
What's the status of reverse proxy?

### ISSUE THREAD

**Issue by lindesvard** [hyperdxio/hyperdx#510]
Hey,

First of all I just want to say **thanks for an amazing project**.

Curious whats the status for reverse proxies? Currently it feels hard to achieve and the only way I get this to work is without SSL and using my ip address to the VPS or I might be missing something but the docs is lacking around this area.

Some related issues:
- https://github.com/hyperdxio/hyperdx/issues/441
- https://github.com/hyperdxio/hyperdx/pull/14
- https://github.com/hyperdxio/hyperdx/issues/12

**Comment by MikeShi42** [comment]
@lindesvard totally hear you, this is something we're looking to address in our v2 release to make it easier to self-host with a custom domain. Fwiw for SSL it'll still require a user to set up their preferred reverse proxy for SSL certs themselves (nginx, caddy, etc) - but the v2 release should make it substantially easier to do so without re-building images and dealing with multiple containers.

In v1 you'll need to rebuild the frontend image to bake in the custom domain and host both frontend/backend containers behind a reverse proxy to achieve that. We know it's not ideal and we're looking to streamline that for v2 with a more simplified deployment method.

**Comment by lindesvard** [comment]
Thanks, looking forward to v2 🔥
