### ISSUE TITLE
[HDX-43] Custom ingestion API domain or proxy docs

### ISSUE THREAD

**Issue by TobbenTM** [hyperdxio/hyperdx#52]
An issue with the browser JS package is that it ships everything to https://in-otel.hyperdx.io which is already on a lot of blocklists, ensuring that most useful events are dropped.
This means both lost insights for users of HyperDX Cloud, but also less revenue because of less data ingestion.
Of course, this is only relevant for HyperDX Cloud, not the self-hosted one which is already hosted on a owned domain.

So this is one of two things:
1. A feature request for custom domain names for the HyperDX Cloud ingestion API (where HyperDX hosts the proxy with SSL termination)
2. A docs request for how to most effectively set this up ourselves without messing with the data that the ingestion expects (does it look at origin/host? does it handle forwarded headers?)

<sub>[HDX-43](https://linear.app/hyperdx/issue/HDX-43/custom-ingestion-api-domain-or-proxy-docs)</sub>

**Comment by MikeShi42** [comment]
A bit shocked at how fast we got on those lists, also a casualty of having ad block disabled on our own site for development reasons 😅

I think in the short term we'll likely recommend users set up an otel collector that simply intakes and forwards the data to our otel ingestion endpoint (the browser package is 100% opentelemetry, so a pass through collector should just work) if they'd like. The docs shouldn't be too hard, though I know it's not ideal having to stand up a public-facing service.

The first option definitely sounds interesting, though I'll need to dig in a bit more.
