### ISSUE TITLE
[HDX-45] Suppress Services' Logs

### ISSUE THREAD

**Issue by wrn14897** [hyperdxio/hyperdx#54]
Users should be able to suppress HyperDX services' logs by setting env vars like 'HDX_LOG_LEVEL'

**Comment by Seikilos** [comment]
FYI: 
Tried to use hyperdx at work behind a fairly crazy amount of proxy and whitelisting-only IT sec and failed.

Docker registry is fine, but when it comes to `make build-local` because I have to change the `.env` file, there is currently no way to do it for us because many urls are blocked. If changing log level will also mean changing `.env` file, then we are out of luck :/

**Comment by wrn14897** [comment]
> FYI: Tried to use hyperdx at work behind a fairly crazy amount of proxy and whitelisting-only IT sec and failed.
> 
> Docker registry is fine, but when it comes to `make build-local` because I have to change the `.env` file, there is currently no way to do it for us because many urls are blocked. If changing log level will also mean changing `.env` file, then we are out of luck :/

`make build-local` is mainly for rebuilding the frontend app. In this case, you can just pull the code and restart the docker containers and log level should be applied (we will publish new images if code update is required). For frontend (or any services) logs/traces, you can remove `HYPERDX_API_KEY` env var if you don't want those to be recorded

**Comment by Seikilos** [comment]
> > FYI: Tried to use hyperdx at work behind a fairly crazy amount of proxy and whitelisting-only IT sec and failed.
> > Docker registry is fine, but when it comes to `make build-local` because I have to change the `.env` file, there is currently no way to do it for us because many urls are blocked. If changing log level will also mean changing `.env` file, then we are out of luck :/
> 
> `make build-local` is mainly for rebuilding the frontend app. In this case, you can just pull the code and restart the docker containers and log level should be applied (we will publish new images if code update is required). For frontend (or any services) logs/traces, you can remove `HYPERDX_API_KEY` env var if you don't want those to be recorded

But isn't rebuilding required, when I at least change localhost to an internal server IP (this is unrelated to log verbosity though)?

**Comment by wrn14897** [comment]
> > > FYI: Tried to use hyperdx at work behind a fairly crazy amount of proxy and whitelisting-only IT sec and failed.
> > > Docker registry is fine, but when it comes to `make build-local` because I have to change the `.env` file, there is currently no way to do it for us because many urls are blocked. If changing log level will also mean changing `.env` file, then we are out of luck :/
> > 
> > 
> > `make build-local` is mainly for rebuilding the frontend app. In this case, you can just pull the code and restart the docker containers and log level should be applied (we will publish new images if code update is required). For frontend (or any services) logs/traces, you can remove `HYPERDX_API_KEY` env var if you don't want those to be recorded
> 
> But isn't rebuilding required, when I at least change localhost to an internal server IP (this is unrelated to log verbosity though)?

You can lock your 'app' service image version (in compose file) and you don't need to rebuild images since other services should be able to read URL env var dynamically. For frontend session recording specifically, the api key is sent from the next server so it should be okay to remove HYPERDX_API_KEY without rebuilding as well

**Comment by wrn14897** [comment]
The issue should be fixed (https://github.com/hyperdxio/hyperdx/pull/66). Check out [readme](https://github.com/hyperdxio/hyperdx#how-to-suppress-all-logs-from-hyperdx-itself-) for details
