### ISSUE TITLE
.env uses 1.1.2 image version for 1.1.3

### ISSUE THREAD

**Issue by Seikilos** [hyperdxio/hyperdx#71]
Is it correct, that `.env` uses the 1.1.2 version?
https://github.com/hyperdxio/hyperdx/blob/e7036dea42def0ba3ef6e84a1f1c79b4a5089961/.env#L3C1-L3C20

**Comment by wrn14897** [comment]
That commit is releasing images. The version bump is in the [next commit](https://github.com/hyperdxio/hyperdx/commit/01ee449145f1d40e13cb093aefb8e236cfa04bfe). I think next time we will ship them together (unless we don't want to rollout immediately)
