### ISSUE TITLE
[HDX-142] Support non numeric values for histogram

### ISSUE THREAD

**Issue by Seikilos** [hyperdxio/hyperdx#94]
I am test-driving hyperdx and IMHO the best thing on observability tools is to slice and dice data into several segments to understand and inspect things.

I realized that I have many events being sent from various nodes. The data looks something like:

```json
{
  "Duration": 345,
  "Node": "A"
}
```

Another would be 

```json
{
  "Duration": 25555,
  "Node": "B"
}
```
I now want to see a histogram binned by Node Name and their durations.
While I can create a histogram about Duration and filter to `Node:"B"`, I would rather be able to create the following histogram:
"Show me the (pick one: average|min|max) duration for Service X, grouped by 'Node'".

I assumed this would be a very common use case. But I might be wrong 😅

As far as I can see, HyperDX does not support it right now. If so, then this is a feature request, otherwise this is a request to help me to find the docs for it 😊

Edit: The line chart actually has an ok-ish visualization for that (if there is more than one data point), but maybe a histogram feature set similar to the line chart would be useful?

<sub>[HDX-142](https://linear.app/hyperdx/issue/HDX-142/support-non-numeric-values-for-histogram)</sub>

**Comment by MikeShi42** [comment]
Hi @Seikilos I'm wondering if you'd be looking for a table in this case if you want a single data point?

<img width="1193" alt="image" src="https://github.com/hyperdxio/hyperdx/assets/2781687/b448a0bd-8df2-41a9-befb-e99edffd2070">

if not, could you share maybe an example image of the kind of visualization you'd be looking for?

**Comment by Seikilos** [comment]
Hi @MikeShi42 
the table is ok for that, but for visually detecting patterns, tables usually fails.

Here is an excel example:
![grafik](https://github.com/hyperdxio/hyperdx/assets/1260908/5e375649-cd1a-43ad-bb1b-21790b884bd6)

I can visually spot, that B is off much easier form a chart. Additionally I can instantly see that C is also probably something to look at.

**Comment by MikeShi42** [comment]
Ahh got it, sorry the word histogram is so overloaded in our app that it took me a minute to get aligned with what you're saying 😅

Totally makes sense - functionally it'll be like our table chart, but being able to visualize the values as bars as well (which is now clicking with me that's what you meant the whole time). This shouldn't be too hard to pull off.

I'm curious what do you think of a combined histogram/table display if it'd help? (crude mockup)

<img width="1004" alt="image" src="https://github.com/hyperdxio/hyperdx/assets/2781687/bc532d45-639f-467a-864c-9a828476a347">

**Comment by Seikilos** [comment]
@MikeShi42 how do you overload this word? For what did you guys use it as well?

The table+chart looks great. 👍 Would be very useful. One caveat: The histogram page would need some kind of hint that the functionality that others would 'naturally' search in the histogram tab (as I did) is actually in the table. 😊

**Comment by MikeShi42** [comment]
Yeah discoverability would definitely be an issue... will need to chew on that a bit more to figure out what we can do there.

For overloading, I guess the two "histograms" we have today are either binned by timestamp (bar chart on the search page), or binned by numeric bucket (histogram chart type, which can bin by number values like 5ms - 15ms, etc.). I'm going to need to do some digging to figure out how to straighten when/how we should talk about histograms in the app.
